// Auto-generated search index of SMT tools (mirrors features/index.html).
window.SMT_TOOLS = [
  { n: "IP Geolocator", t: "ip location geolocation" },
  { n: "IP Pinger", t: "ip ping network" },
  { n: "IP Logger", t: "ip logger tracking" },
  { n: "IP Stealer", t: "ip stealer capture" },
  { n: "NS Lookupper", t: "dns nslookup domain" },
  { n: "Internet Route Tracer", t: "traceroute network path" },
  { n: "Network Speedtest", t: "speedtest bandwidth" },
  { n: "Wi-Fi Password Revealer", t: "wifi password reveal" },
  { n: "Website Blocker", t: "block website filter" },
  { n: "Easy DNS Changer", t: "dns change switch" },
  { n: "SMB Bruteforcer", t: "smb brute force" },
  { n: "URL Shortener", t: "url short link" },
  { n: "IPv6 Disabler", t: "ipv6 disable network" },
  { n: "IPv6 Re-enabler", t: "ipv6 enable network" },
  { n: "CLI Task Manager", t: "task manager process cli" },
  { n: "Tron", t: "tron clean disinfect repair" },
  { n: "U* Miner Remover", t: "xmrig miner virus usb remover" },
  { n: "Hibernation Enabler/Disabler", t: "hibernate sleep power" },
  { n: "Registry Backupper", t: "registry backup restore" },
  { n: "Driver Backupper", t: "driver backup restore" },
  { n: "System Info Viewer", t: "system info hardware" },
  { n: "Create A System Restore Point", t: "system restore point rollback" },
  { n: "Folder Organizer", t: "organize files folders" },
  { n: "Hydra Launcher", t: "hydra games launcher" },
  { n: "Performance Options", t: "performance windows optimize" },
  { n: "Shutdown & Restart Commands", t: "shutdown restart" },
  { n: "Boot to BIOS", t: "bios restart firmware" },
  { n: "Console Color Changer", t: "color console theme" },
  { n: "Add to PATH", t: "path environment" },
  { n: "Add to Program Files", t: "install program files" },
  { n: "Auto Window Resizing", t: "window resize auto" },
  { n: "Time Freezer", t: "time freeze pause" },
  { n: "Clipboard Manager", t: "clipboard copy paste" },
  { n: "Screenshot Tool", t: "screenshot capture" },
  { n: "Bootable USB Creator", t: "usb boot ventoy" },
  { n: "Uninstaller", t: "uninstall remove" },
  { n: "Any App (winget) Installer", t: "winget any app installer" },
  { n: "App Installer Generator", t: "installer generator app" },
  { n: "Right Click Menu Changer", t: "right click context menu" },
  { n: "Scan Computer for Errors", t: "scan sfc dism errors" },
  { n: "Windows 11 Tweaker", t: "windows 11 tweak" },
  { n: "Ultimate Performance Power Plan Enabler", t: "power plan performance" },
  { n: "Group Policy Editor Enabler", t: "gpedit group policy" },
  { n: "Windows & Office Activator", t: "windows office activation license" },
  { n: "Windows User Manager", t: "user manager password reset" },
  { n: "Windows Password Cracker", t: "password crack recover wsl" },
  { n: "UAC Disabler", t: "uac disable administrator" },
  { n: "Proton VPN", t: "proton vpn privacy" },
  { n: "Extension Manifest V2 Extender", t: "chrome extension manifest v2" },
  { n: "Some Settings Managed Fixer", t: "settings managed organization fix" },
  { n: "Audacity", t: "audacity audio editor" },
  { n: "Text to Speech", t: "text speech tts" },
  { n: "Info Stealer Generator", t: "info stealer generator payload" },
  { n: "Node.js", t: "node nodejs javascript" },
  { n: "File Integrity Checker", t: "hash integrity checksum" },
  { n: "RockYou Downloader", t: "rockyou wordlist password" },
  { n: ".zip Password Cracker", t: "zip password crack recover" },
  { n: "Credentials Storer", t: "credentials store vault" },
  { n: "Malwarebytes Premium Resetter", t: "malwarebytes reset premium" },
  { n: "Bitdefender Free", t: "bitdefender antivirus free" },
  { n: "Anti-Piracy Measures", t: "anti-piracy protection" },
  { n: "User Agreement", t: "user agreement terms" },
  { n: "Logitech G HUB", t: "logitech hub peripherals" },
  { n: "Chrome Installer", t: "chrome browser google" },
  { n: "Firefox Installer", t: "firefox browser" },
  { n: "Geek Uninstaller", t: "geek uninstaller clean" },
  { n: "7-Zip Installer", t: "7zip archive compress" },
  { n: "Git Installer", t: "git version control" },
  { n: "Winget Installer", t: "winget package manager" },
  { n: "SuperF4 Installer", t: "superf4 force close" },
  { n: "Powershell 7 Installer", t: "powershell pwsh shell" },
  { n: "f.lux Installer", t: "flux screen temperature" },
  { n: "OBS Studio", t: "obs studio stream record" },
  { n: "Wintoys Installer", t: "wintoys utility" },
  { n: "Windows PC Manager Installer", t: "pc manager microsoft" },
  { n: "Fastfetch Installer", t: "fastfetch neofetch system" },
  { n: "Telegram Installer", t: "telegram messenger" },
  { n: "Malwarebytes Installer", t: "malwarebytes antivirus" },
  { n: "Notepad++ Installer", t: "notepad++ editor" },
  { n: "Command Prompt", t: "cmd command prompt" },
  { n: "Powershell", t: "powershell shell" },
  { n: "Powershell (Installer)", t: "powershell installer pwsh" },
  { n: "Chris Titus Tool", t: "chris titus toolbox" },
  { n: "ShareX", t: "sharex screenshot recorder" },
  { n: "qBittorrent", t: "qbittorrent torrent" },
  { n: "Paint.NET", t: "paint.net image editor" },
  { n: "Everything", t: "everything file search" },
  { n: "Github Desktop", t: "github desktop git" },
  { n: "Ultimate Windows Tweaker", t: "ultimate windows tweaker" },
  { n: "Recuva", t: "recuva recovery" },
  { n: "Process Hacker", t: "process hacker taskmanager" },
  { n: "Winaero Tweaker", t: "winaero tweaker" },
  { n: "Discord", t: "discord chat" },
  { n: "Vencord", t: "vencord discord mod" },
  { n: "IrfanView", t: "irfanview image viewer" },
  { n: "Playit.gg", t: "playit.gg tunnel" },
  { n: "Prism Launcher", t: "prism launcher minecraft" },
  { n: "SKLauncher", t: "sklauncher minecraft" },
  { n: "Blip", t: "blip github downloader" },
  { n: "CapCut Pro", t: "capcut video editor" },
  { n: "RustDesk", t: "rustdesk remote desktop" },
  { n: "AnyDesk", t: "anydesk remote desktop" },
  { n: "Win10 Widgets + Rainmeter 4.0", t: "rainmeter widgets desktop" },
  { n: "Rainmeter", t: "rainmeter desktop" },
  { n: "Spotify (No Ads)", t: "spotify adblock" },
  { n: "ASCII Art Generator", t: "ascii art text gradient" },
  { n: "ASCII Art Logo", t: "ascii logo art" },
  { n: "Portable Creator", t: "portable zip package" },
  { n: "Secret Commands", t: "secret commands hidden" },
  { n: "Command History", t: "command history" },
  { n: "Debug Mode", t: "debug troubleshooting" },
  { n: "Open CMD / PowerShell", t: "cmd powershell terminal" },
  { n: "Git Command", t: "git command" },
  { n: "Chocolatey", t: "chocolatey package manager" },
  { n: "Auto Update System", t: "auto update" },
  { n: "Steam", t: "steam games" },
  { n: "Password Generator", t: "password generator secure" },
  { n: "ASCII Art Gradient Generator", t: "ascii gradient art" },
  { n: "Directory File Line Counter", t: "directory line counter files" },
  { n: "Batch File Creator", t: "batch file creator" },
  { n: "Minecraft Server Creator", t: "minecraft server" },
  { n: "MegaTemp", t: "mega account manager" },
  { n: "Private Folder Manager", t: "private folder lock" },
  { n: "School Utilities", t: "school education student" },
  { n: "Command-Line Game", t: "game cli fun" },
  { n: "Windows Destroyer", t: "destroy danger zone" },
  { n: "Danger Zone Group", t: "danger zone destructive" },
  { n: "Mystery Advanced Tool", t: "mystery surprise" },
  { n: "ExifCleaner", t: "exif metadata cleaner" },
  { n: "Schnuker", t: "schnuker network utility" },
  { n: "Keyviz", t: "keyviz keystrokes" },
  { n: "Info (About SMT)", t: "info about version" },
  { n: "Python Install Manager", t: "python" },
  { n: "utilman Trick Applier", t: "utilman accessibility trick" },
  { n: "Info Stealer (OLD)", t: "info stealer legacy research" },
  { n: "Disk Space Filler", t: "disk fill danger test" },
  { n: "FGRDown", t: "fitgirl repack downloader" }
];
